server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.177.44.94:3306/equi-db?serverTimezone=GMT%2b8
    username: root
    password: 155786

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    # 驼峰关闭可解决数据查询不全问题

#imgUploadPath: D:\img\
imgUploadPath: /home/bz/equipmanage/image/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  enable-spring-security:
    false
